baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 10

[[menu.main]]
  name = "about"
  weight = 1
  identifier = "about"
  url = "#about"

[[menu.main]]
  name = "getting started"
  weight = 2
  identifier = "getting-started"
  url = "#getting-started"

[[menu.main]]
  name = "donate"
  weight = 3
  identifier = "donate"
  url = "#donate"

[[menu.main]]
  name = "updates"
  weight = 4
  identifier = "updates"
  url = "#updates"

[params]
  DiscordURL = "https://discord.gg/gz9pz97"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  ProjectName = "Yuzu Emulator Team"

[Languages]
  [Languages.en]
    title = "yuzu"
    tagline = "An experimental Nintendo Switch Emulator"
    description = "Yuzu is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "JSON" ]