baseurl = "https://yuzu-emu.org/"
languageCode = "en-us"

DefaultContentLanguage = "en"
theme = "shared-bulma-theme"

# Define how many objects appear per pagination.
paginate = 10

[[menu.main]]
  name = "frequently asked questions"
  weight = 1
  identifier = "faq"
  url = "#faq"

[[menu.main]]
  name = "contributing"
  weight = 2
  identifier = "contribute"
  url = "#contribute"

[[menu.main]]
  name = "updates"
  weight = 3
  identifier = "updates"
  url = "#updates"

[params]
  DiscordURL = "https://discord.gg/gz9pz97"
  TwitterURL = "https://twitter.com/yuzuemu"
  GithubURL = "https://github.com/yuzu-emu/yuzu"
  ProjectName = "yuzu Emulator Project"

[Languages]
  [Languages.en]
    title = "yuzu"
    tagline = "An experimental Nintendo Switch Emulator"
    description = "Yuzu is a highly experimental open-source emulator for the Nintendo Switch."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "JSON" ]